apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: wangwg2/hyperkube-amd64:__RELEASE__
    command:
      - /hyperkube
      - scheduler
      - --pod-infra-container-image=wangwg2/pause-amd64:3.0
      - --master=http://__MASTER_IP__:8080
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1