apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: wangwg2/hyperkube-amd64:__RELEASE__
    command:
      - /hyperkube
      - proxy
      - --pod-infra-container-image=wangwg2/pause-amd64:3.0
      - --master=http://__MASTER_IP__:8080
      - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - name: ssl-certs-host
    hostPath:
      path: /usr/share/ca-certificates
